spring:
  h2:
    console:
      enabled: true
      path: /backbone
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:backbone;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true